### PR TITLE
fix build issue

### PR DESCRIPTION
**Pull request by rajcspsg**
@stanch - This is to fix the build issue.

### CODE REVIEW

**Comment by stanch** [comment]
Just migrated the Travis integration to travis-ci.com so that it can comment here... I think the build is still failing, let’s see.

**Comment by rajcspsg** [comment]
do you mind if I drop support for scala 2.11 version? The cross build is causing lot of trouble with transitive dependency version.

**Comment by stanch** [comment]
> do you mind if I drop support for scala 2.11 version? The cross build is causing lot of trouble with transitive dependency version.

Sure, makes sense to me. No point in supporting 2.11, 2.12 and 2.13 all at the same time. (And I think 2.11 has reached end of life?)

**Comment by rajcspsg** [comment]
yeap 2.11 is already EOL

**Comment by rajcspsg** [comment]
@stanch I removed the 2.11 crossScalaVersion

**Pull request merged**
